[package]
name = "map_generator"
version = "0.1.0"
authors = ["Wout Schellaert <wout.schellaert@gmail.com>"]

[dependencies]
rand = "0.3.17"
itertools = "0.7.2"
num = "0.1.40"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0"