const path = require('path');

const merge = require('webpack-merge');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const baseConfig = require('./webpack.config.base');

module.exports = merge(baseConfig, {
  entry: ['./bin/index'],
  mode: 'development',
  watch: true,
  plugins: [
    // For the test index.html
    new CopyWebpackPlugin([{
      from: '../*.html'
    }])
  ],
  devtool: "source-map",
  devServer: {
    contentBase: path.join(__dirname, '..'),
    port: 8080
  },
  module: {
    rules: [{
      test: /\.global\.scss$/,
      use: ['style-loader', 'css-loader?sourceMap', 'sass-loader']
    },
    {
      test: /^((?!\.global).)*\.scss$/,
      use: [
        'style-loader',
        {
          loader: 'typings-for-css-modules-loader',
          options: {
            modules: true,
            sourceMap: true,
            importLoaders: 1,
            namedExport: true,
            banner: "// This file is automatically generated by typings-for-css-modules.\n// Please do not change this file!",
            localIdentName: '[name]__[local]__[hash:base64:5]',
          }
        },
        'sass-loader',
      ]
    },
    ]
  }
});